- hosts: all
  become: true
  tasks:
    - name: Instalar git
      apt: name=git state=present update_cache=true
    - name: Instalar postgresql
      apt: name=postgresql state=present
    - name: Instalar nginx
      apt: name=nginx state=present